### ISSUE TITLE
[Design] Simplify document structure (for pre-processors)

### ISSUE THREAD

**Issue by mlange-42** [mlange-42/yarner#133]
Currently, code and text blocks in `Document` are passed as one `Line` and `String` entry per line, respectively.

## Text blocks

For text blocks, it would be possible to concat all lines into a single string, either 1) during parsing or 2) during JSON serialization

Problems:

Option 1):  Before/during writing, the correct newlines must be ensured

Option 2): Yarner and pre-processors must use different `TextBlock` types. Joinging would happen during serialization, while splitting would happen during de-serialization.

## Code blocks

Code block lines contain some more information, like `indent` and `comment`. The latter could be removed if the comment extraction feature is dropped. Then, successive code lines that are no macros could also be joined into a single string, but it not as clear and usable as for text blocks.

**Comment by adamreichold** [comment]
> Currently, code and text blocks in Document are passed as one Line and String entry per line, respectively.

I am not sure if this is actually making it more complicated for preprocessors? Won't they often work line by line as well? It might be a bit inefficient, but providing a schema that uses e.g. `Cow<'a, str>` to support both owned and borrowed (zero-copy) text representations would probably be more efficient than just collapsing text block lines.

**Comment by mlange-42** [comment]
Yes, it would add something like `lines()` for pre-processors. And, I didn't consider that, make it more complicated to insert lines into text blocks. In most cases, simply adding text blocks would be sufficient, but probably not in all cases.

A problem might be that multi-line entries in the vector of lines is possible, potentially introducing the wrong line endings. However, this could be fixed by Yarner on the received documents.

I think I will revert the lines thing.

For a trial including simplifications on `CodeBlock`, see #134.

**Comment by adamreichold** [comment]
> A problem might be that multi-line entries in the vector of lines is possible, potentially introducing the wrong line endings. However, this could be fixed by Yarner on the received documents.

I am not sure if the main program should be obligated to fix errors introduced by the preprocessors. If the document model includes lists of lines, then that is the contract a preprocessor has to fulfil.

**Comment by mlange-42** [comment]
At least, as the newline is accessible in `Document`, this should be well possible.

**Comment by mlange-42** [comment]
I just realized that it is not as simple as `flat_map(|l| l.lines()).join`... to fix potential newlines, as `lines()` ignores newlines at the end of the string :(

So I will leave it for now.

**Comment by mlange-42** [comment]
Done in #134
