### ISSUE TITLE
[Plugin] A plugin to execute arbitrary commands on the code

### ISSUE THREAD

**Issue by mlange-42** [mlange-42/yarner#150]
Could be used to bundle necessary steps like testing, linter, etc. into a single command. Does that make sense...?

**Comment by adamreichold** [comment]
> Could be used to bundle necessary steps like testing, linter, etc. into a single command. Does that make sense...?

Only if Yarner should become a replacement for a build tool as well. Otherwise, something like
```
> yarner && cargo --manifest-path=code/Cargo.toml test
```
should suffice.
