### ISSUE TITLE
[Documentation] Document TOML options that are absent by default

### ISSUE THREAD

**Issue by mlange-42** [mlange-42/yarner#19]
* [x] `default_language`
* [x] `entrypoint` (to be implemented, see #17)

**Comment by adamreichold** [comment]
It might make sense to put these into the templates, but comment them out by default?

**Comment by mlange-42** [comment]
@adamreichold Great idea! Why did I not think of it...?

**Comment by mlange-42** [comment]
Implemented in d16fb0e
