### ISSUE TITLE
Rename sub-commands to use more common names?

### ISSUE THREAD

**Issue by mlange-42** [mlange-42/yarner#42]
Re-think sub-command naming to better conform with 'standards'

* Use `init` instead of `create`?
* Use `build` instead of nothing?

**Comment by mlange-42** [comment]
@adamreichold What do you think?

**Comment by adamreichold** [comment]
I have no real preference with regards to `init` versus `create`. Having a `build` verb makes sense, but I think it should stay the default when omitted as it is by far the most common invocation.

**Comment by mlange-42** [comment]
Thanks for sharing your opinion. So if you don't see it as inconsistency, I will probably leave it as is. Also, I noticed that `init` does in most cases need no arguments, while `create` here does.
