### ISSUE TITLE
[Feature] Make meta variables a feature to be activated explicitly, as it collides with reverse mode.

### ISSUE THREAD

**Issue by mlange-42** [mlange-42/yarner#74]
Meta variables should not be allowed by default.

Make it a feature to be explicitly activated, e.g. by wrapping the three related `toml` options into an optional struct.
Should we then detect if it is enabled and any language is set up for reverse mode, and emit a warning?

Also mention the limitation is the guide.

**Comment by mlange-42** [comment]
@adamreichold Realized that starting to crack settings out of the parser might motivate that all settings become just `ParserSettings`. Then, the `MdParser` could go away completely, and everything inside could become simple module functions. So maybe this should be done during/after the general restructuring (#57)?

**Comment by adamreichold** [comment]
> So maybe this should be done during/after the general restructuring (#57)?

It is certainly aligned with that approach, but I would not make it dependent on that refactoring. There is also an intermediate state where the parser settings are within a `ParserSettings` struct in the `config` module and `MdParser` is unit-like struct without any fields.

**Comment by mlange-42** [comment]
Already implemented as an intermediate state in #75.

**Comment by mlange-42** [comment]
Decided to remove that feature completely.
