### ISSUE TITLE
[Bug] Simplify block label paths when containing `..`

### ISSUE THREAD

**Issue by mlange-42** [mlange-42/yarner#92]
E.g. this:

```
// <@experiments\../resources/random.md#file:src/resources/random.rs#0
```

should instead look like this:

```
// <@resources/random.md#file:src/resources/random.rs#0
```

(This kind of paths occurs through transclusions)

**Comment by adamreichold** [comment]
Isn't this closed via #93?

**Comment by mlange-42** [comment]
Yes. It is linked to the MR, but probably GH closes it only when merged into master.

**Comment by adamreichold** [comment]
> Yes. It is linked to the MR, but probably GH closes it only when merged into master.

Yeah, this is one of the mismatches between the assumptions coded into GitHub and git-flow. It might make sense to make `dev` the default branch though as `master` is basically used only to prepare releases anyway.

**Comment by mlange-42** [comment]
I was already considering that, but was not sure if `dev` would then also be the branch displayed on the repo page as default. Actually, ma primary reason to still stick with git-flow is to always have the README etc. (incl. code) always represent the latest release rather than showing information that represents changes that are not released yet.

**Comment by adamreichold** [comment]
> Actually, ma primary reason to still stick with git-flow is to always have the README etc. (incl. code) always represent the latest release rather than showing information that represents changes that are not released yet.

As with the multiple crates per repo issue, this could be resolved by publishing to crates.io which displays the README from the published crate version.

**Comment by mlange-42** [comment]
But only on crates.io, not on GH 😉
